"""init schema

Revision ID: d6ad9cc675d1
Revises: 
Create Date: 2026-07-23 00:09:07.976122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ad9cc675d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_type', sa.String(length=30), nullable=False),
    sa.Column('business_object_type', sa.String(length=30), nullable=False),
    sa.Column('business_object_id', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('parsed_output_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsibility_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_attendance', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.String(length=40), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=False),
    sa.Column('after_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('embedding_reference', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_roles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('activity_id', sa.String(length=40), nullable=False),
    sa.Column('role_id', sa.String(length=40), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('resource_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('activity_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('map_file_url', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('activity_id', sa.String(length=40), nullable=False),
    sa.Column('scene_id', sa.String(length=40), nullable=True),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_impact', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('structured_data_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_areas',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scene_id', sa.String(length=40), nullable=False),
    sa.Column('area_name', sa.String(length=200), nullable=False),
    sa.Column('area_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('current_version_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('confirmed_by', sa.String(length=40), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('current_version_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_by', sa.String(length=40), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieval_records',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('selected_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('structured_content_json', sa.JSON(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('citation_json', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('report_id', sa.String(length=40), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('structured_content_json', sa.JSON(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('statistics_json', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('plan_version_id', sa.String(length=40), nullable=False),
    sa.Column('task_code', sa.String(length=50), nullable=False),
    sa.Column('task_name', sa.String(length=300), nullable=False),
    sa.Column('role_id', sa.String(length=40), nullable=False),
    sa.Column('phase_code', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('trigger_condition', sa.Text(), nullable=True),
    sa.Column('planned_start_offset', sa.Integer(), nullable=True),
    sa.Column('deadline_minutes', sa.Integer(), nullable=True),
    sa.Column('required_people', sa.Integer(), nullable=True),
    sa.Column('required_resources_json', sa.JSON(), nullable=False),
    sa.Column('collaborating_roles_json', sa.JSON(), nullable=False),
    sa.Column('dependencies_json', sa.JSON(), nullable=False),
    sa.Column('completion_criteria', sa.Text(), nullable=False),
    sa.Column('feedback_requirement', sa.Text(), nullable=True),
    sa.Column('exception_action', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['plan_version_id'], ['plan_versions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_executions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executor', sa.String(length=100), nullable=True),
    sa.Column('execution_result', sa.Text(), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('temporary_adjustments', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_executions')
    op.drop_table('tasks')
    op.drop_table('report_versions')
    op.drop_table('plan_versions')
    op.drop_table('retrieval_records')
    op.drop_table('reports')
    op.drop_table('plans')
    op.drop_table('scene_areas')
    op.drop_table('events')
    op.drop_table('scenes')
    op.drop_table('activity_roles')
    op.drop_table('knowledge_chunks')
    op.drop_table('audit_logs')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('knowledge_documents')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
